---
abstract: 'Imports all modules relevant to sequence mapping'
author:
  - 'Christos Argyropoulos <chrisarg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.032, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-SeqAlignment-Components-SeqMapping
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Bio::SeqAlignment::Components::SeqMapping:
    file: lib/Bio/SeqAlignment/Components/SeqMapping.pm
    version: '0.01'
  Bio::SeqAlignment::Components::SeqMapping::Dataflow:
    file: lib/Bio/SeqAlignment/Components/SeqMapping/Dataflow.pm
    version: '0.01'
  Bio::SeqAlignment::Components::SeqMapping::Dataflow::Linear:
    file: lib/Bio/SeqAlignment/Components/SeqMapping/Dataflow/Linear.pm
    version: '0.01'
  Bio::SeqAlignment::Components::SeqMapping::Dataflow::LinearGeneric:
    file: lib/Bio/SeqAlignment/Components/SeqMapping/Dataflow/LinearGeneric.pm
    version: '0.01'
  Bio::SeqAlignment::Components::SeqMapping::Dataflow::LinearLinear:
    file: lib/Bio/SeqAlignment/Components/SeqMapping/Dataflow/LinearLinear.pm
    version: '0.01'
  Bio::SeqAlignment::Components::SeqMapping::Dataflow::LinearLinearGeneric:
    file: lib/Bio/SeqAlignment/Components/SeqMapping/Dataflow/LinearLinearGeneric.pm
    version: '0.01'
  Bio::SeqAlignment::Components::SeqMapping::Mapper:
    file: lib/Bio/SeqAlignment/Components/SeqMapping/Mapper.pm
    version: '0.01'
  Bio::SeqAlignment::Components::SeqMapping::Mapper::Generic:
    file: lib/Bio/SeqAlignment/Components/SeqMapping/Mapper/Generic.pm
    version: '0.01'
requires:
  Carp: '0'
  MCE: '0'
  MCE::Candy: '0'
  Module::Find: '0'
  Module::Runtime: '0'
  Moose: '0'
  Moose::Role: '0'
  Scalar::Util: '0'
  namespace::autoclean: '0'
  strict: '0'
  warnings: '0'
version: '0.01'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
